### ISSUE TITLE
CoreNLP and NER dependency issue

### ISSUE THREAD

**Issue by divija96** [aoldoni/tetre#33]
Hi,
I am  following the instructions in your ReadME and as mentioned I am trying to find the source for CoreNLP 3.6.0 but I am unable to do so. Could you share the link for the same?

**Comment by aoldoni** [comment]
Hi, @divija96 - this link https://stanfordnlp.github.io/CoreNLP/history.html seems to contain all versions for downloading 👍

**Comment by divija96** [comment]
I had referred to the link that you sent. It contains links to the zips which contain jar files whereas as mentioned in your readme, I should be looking for one with the src so that I can replace it's contents with https://github.com/aoldoni/stanford-corenlp. The only other way of getting the src of 3.6.0 is through corenlp's  GitHub page but it isn't convenient since they do not have the versions segregated in the form of releases. Sorry for the inconvenience and thanks in advance :)

**Comment by divija96** [comment]
@aoldoni Can you please look into this?

**Comment by aoldoni** [comment]
Hi @divija96 ,

Sorry for the late response. Please note the following:
- This link contains the 3.6.0 release: https://stanfordnlp.github.io/CoreNLP/history.html
- Once you download the zip file, please decompress it. You will find a file named "stanford-corenlp-3.6.0-sources.jar", which contains the sources.
- Once you decompress this file again, you will find the source files.

Anyhow, the whole source for 3.6.0 with the modifications to train for different entities and relations is already in the https://github.com/aoldoni/stanford-corenlp repo, so I believe you shouldn't need the original. You may follow back the commits at that repo, and then found the unchanged 3.6.0 source code as well - e.g.: the first commit at the bottom of this page https://github.com/aoldoni/stanford-corenlp/commits/master

Thanks.

**Comment by divija96** [comment]
Hi,
Yes, we managed to figure that out. Thanks for your help though. Your work
was really inspired and thoughtful and so was your coding style. After
looking at your approach we were thinking if there could be a way to
automate the formulation of rules themselves and experimented with several
machine comprehension based models. Your work did put us in the right
direction. Hearty thanks for that.

Cheers,
Divija Nagaraju



‌

**Comment by aoldoni** [comment]
Hi @divija96 ,

This is very good to hear! I am glad that what I did helped someone! :+1: 
If it's possible to see what you achieved published anywhere, please send the link through!

Again, thanks!
