### ISSUE TITLE
process killed 

### ISSUE THREAD

**Issue by anfiallos** [aoldoni/tetre#34]
Hello, i try to run the commad:
./bin/tetre extract --tetre_word improves --tetre_output html
but, the process is killed. I use Ubuntu and python 3.5

(.env) ubuntu@ip-172-31-22-210:~/.local/lib/python3.5/tetre$ ./bin/tetre extract --tetre_word improves --tetre_output html
Killed
(.env) ubuntu@ip-172-31-22-210:~/.local/lib/python3.5/tetre$

**Comment by aoldoni** [comment]
Hi @timbilino ,

Thanks for your question.

I am sorry, I've never seen such an issue. It sounds like this may happen once Python uses too much memory. For an example, see this thread: https://apple.stackexchange.com/questions/167540/how-do-i-diagnose-my-python-program-being-killed-due-to-an-out-of-memory-error - other reports on "the internet" seems to point in the same direction.

Even though the above link is in regards to MacOS, note how the questioner mentioned he/she was able to solve the problem by using a large swap in Linux.

I am not sure how many files are in your data folder, but please bear in mind that TETRE has a limitation in which it loads all sentences in memory at the same time. I would suggest maybe doing a search on only a smaller subset of the data to see if the problem persists?

If it does work on a subset, I would suggest running the tool on subsets of data at once, and then merging the results elsewhere for now (might be easier doing this using the json output).

Hope it helps.

Thanks!

**Comment by aoldoni** [comment]
Closed due to inactivity.
